### PR TITLE
fix: Remove timeout redirect

### PR DESCRIPTION
**Pull request by ramonklanke**
page will be the same if user doesn't have the app on their device

### CODE REVIEW

**Review by timwb — DISMISSED** [review]
I can't test this, but I trust you completely :)

**Comment by MrSeccubus** [comment]
Please don't merge this! Merge #7 instead.

**Review by MrSeccubus — APPROVED** [review]
Thank you.

**Review by timwb — COMMENTED** [review]
Not sure what the best value for timeout is but let's try :)

**Comment by MrSeccubus** [comment]
It helps...

https://github.com/user-attachments/assets/25c5a983-bf88-4c75-81a0-955f4452778e

**Pull request merged**
